# Generated by Django 5.1.3 on 2024-11-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
